### ISSUE TITLE
Java21 SharedMemory.open Exception

### ISSUE THREAD

**Issue by PhoenixZeng** [ShirasawaSama/JavaSharedMemory#2]
win10
```
SharedMemory sharedMemory = SharedMemory.create("test", 1024);
try (var shm = sharedMemory) {
var buf = shm.toByteBuffer();
buf.put(bytes);

}
System.out.println("write success ");
sharedMemory.close();
SharedMemory test = SharedMemory.open("test", 1024);  // <---
System.out.println(test.getSize());
```
```
WindowsSharedMemory:69

        hMapFile = isCreate ? (MemorySegment) createFileMapping.invokeExact(
                (MemorySegment) MemorySegment.ofAddress(-1),
                MemorySegment.NULL,
                PAGE_READWRITE | SEC_COMMIT,
                0,
                size,
                (MemorySegment) Arena.ofAuto().allocateUtf8String(name)
        ) : (MemorySegment) openFileMapping.invokeExact(SECTION_MAP_WRITE | SECTION_MAP_READ, 0, name);// <--------
        if (hMapFile.address() == 0) throw new IllegalStateException("CreateFileMapping failed.");
```

```
java.lang.RuntimeException: java.lang.invoke.WrongMethodTypeException: handle's method type (int,int,MemorySegment)MemorySegment but found (int,int,String)MemorySegment
	at cn.apisium.shm.SharedMemory.init(SharedMemory.java:86)
	at cn.apisium.shm.SharedMemory.open(SharedMemory.java:54)
	at top.war3rpg.Main.main(Main.java:47)
Caused by: java.lang.invoke.WrongMethodTypeException: handle's method type (int,int,MemorySegment)MemorySegment but found (int,int,String)MemorySegment
	at java.base/java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:522)
	at java.base/java.lang.invoke.Invokers.checkExactType(Invokers.java:531)
	at cn.apisium.shm.impl.WindowsSharedMemory.<init>(WindowsSharedMemory.java:69)
	at cn.apisium.shm.SharedMemory.init(SharedMemory.java:81)
	... 2 more
```

**Comment by ShirasawaSama** [comment]
I will fix this tomorrow.

**Comment by PhoenixZeng** [comment]
只需要把这个name改成 (MemorySegment) Arena.ofAuto().allocateUtf8String(name)好像就好了

**Comment by ShirasawaSama** [comment]
试试0.2.2这个新版本

**Comment by ShirasawaSama** [comment]
是否还有报错，问题是否已经解决？@PhoenixZeng

**Comment by PhoenixZeng** [comment]
解决了
